
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cpp.project1;

import java.awt.Color;
import static java.awt.PageAttributes.MediaType.C;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Priyansh
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    Color DefaultColor,ClickedColor;
    Icon icME,icMI,icMS,icMC,icB,NicME,NicMI,NicMS,NicMC,NicB;
    public admin() {
        initComponents();
        DefaultColor=new Color(0,0,102);
        ClickedColor=new Color(255,255,255);
        
        icME=new ImageIcon("C:\\Users\\chhaj\\Documents\\NetBeansProjects\\cpp project1\\src\\cpp\\project1\\icons\\icons8_management_52px.png");
        icMI=new ImageIcon("C:\\Users\\chhaj\\Documents\\NetBeansProjects\\cpp project1\\src\\cpp\\project1\\icons\\icons8_edit_product_52px.png");
        icMS=new ImageIcon("C:\\Users\\chhaj\\Documents\\NetBeansProjects\\cpp project1\\src\\cpp\\project1\\icons\\icons8_supplier_52px_2.png");
        icMC=new ImageIcon("C:\\Users\\chhaj\\Documents\\NetBeansProjects\\cpp project1\\src\\cpp\\project1\\icons\\icons8_list_52px.png");
        icB=new ImageIcon("C:\\Users\\chhaj\\Documents\\NetBeansProjects\\cpp project1\\src\\cpp\\project1\\icons\\icons8_purchase_order_52px.png");
        
        
        NicME=new ImageIcon("C:\\Users\\chhaj\\Documents\\NetBeansProjects\\cpp project1\\src\\cpp\\project1\\icons\\icons8_management_52px_1.png");
        NicMI=new ImageIcon("C:\\Users\\chhaj\\Documents\\NetBeansProjects\\cpp project1\\src\\cpp\\project1\\icons\\icons8_edit_product_52px_5.png");
        NicMS=new ImageIcon("C:\\Users\\chhaj\\Documents\\NetBeansProjects\\cpp project1\\src\\cpp\\project1\\icons\\icons8_supplier_52px_3.png");
        NicMC=new ImageIcon("C:\\Users\\chhaj\\Documents\\NetBeansProjects\\cpp project1\\src\\cpp\\project1\\icons\\icons8_list_52px_2.png");
        NicB=new ImageIcon("C:\\Users\\chhaj\\Documents\\NetBeansProjects\\cpp project1\\src\\cpp\\project1\\icons\\icons8_purchase_order_52px_2.png");

        
        ManageEmployee.setBackground(DefaultColor);
        ManageItems.setBackground(DefaultColor);
        ManageSuppliers.setBackground(DefaultColor);
        Bills.setBackground(DefaultColor);
        ManageCategory.setBackground(DefaultColor);
        
        ManageEmployee.setIcon(icME);
        ManageItems.setIcon(icMI);
        ManageSuppliers.setIcon(icMS);
        ManageCategory.setIcon(icMC);
        Bills.setIcon(icB);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ManageEmployee = new javax.swing.JLabel();
        ManageSuppliers = new javax.swing.JLabel();
        ManageItems = new javax.swing.JLabel();
        Bills = new javax.swing.JLabel();
        ManageCategory = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        mainpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        AddAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1000));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));

        ManageEmployee.setBackground(new java.awt.Color(0, 0, 102));
        ManageEmployee.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ManageEmployee.setForeground(new java.awt.Color(255, 255, 255));
        ManageEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManageEmployee.setText("MANAGE EMPLOYEE");
        ManageEmployee.setToolTipText("");
        ManageEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ManageEmployee.setOpaque(true);
        ManageEmployee.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ManageEmployeeMouseMoved(evt);
            }
        });
        ManageEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageEmployeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ManageEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ManageEmployeeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ManageEmployeeMousePressed(evt);
            }
        });

        ManageSuppliers.setBackground(new java.awt.Color(0, 0, 102));
        ManageSuppliers.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ManageSuppliers.setForeground(new java.awt.Color(255, 255, 255));
        ManageSuppliers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManageSuppliers.setText("MANAGE SUPPLIERS");
        ManageSuppliers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ManageSuppliers.setOpaque(true);
        ManageSuppliers.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ManageSuppliersMouseMoved(evt);
            }
        });
        ManageSuppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageSuppliersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ManageSuppliersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ManageSuppliersMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ManageSuppliersMousePressed(evt);
            }
        });

        ManageItems.setBackground(new java.awt.Color(0, 0, 102));
        ManageItems.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ManageItems.setForeground(new java.awt.Color(255, 255, 255));
        ManageItems.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManageItems.setText("MANAGE ITEMS");
        ManageItems.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ManageItems.setOpaque(true);
        ManageItems.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ManageItemsMouseMoved(evt);
            }
        });
        ManageItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageItemsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ManageItemsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ManageItemsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ManageItemsMousePressed(evt);
            }
        });

        Bills.setBackground(new java.awt.Color(0, 0, 102));
        Bills.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Bills.setForeground(new java.awt.Color(255, 255, 255));
        Bills.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bills.setText("BILLS");
        Bills.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bills.setOpaque(true);
        Bills.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BillsMouseMoved(evt);
            }
        });
        Bills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BillsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BillsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BillsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BillsMousePressed(evt);
            }
        });

        ManageCategory.setBackground(new java.awt.Color(0, 0, 102));
        ManageCategory.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ManageCategory.setForeground(new java.awt.Color(255, 255, 255));
        ManageCategory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManageCategory.setText("MANAGE CATEGORY");
        ManageCategory.setAutoscrolls(true);
        ManageCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ManageCategory.setOpaque(true);
        ManageCategory.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ManageCategoryMouseMoved(evt);
            }
        });
        ManageCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageCategoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ManageCategoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ManageCategoryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ManageCategoryMousePressed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(0, 0, 102));
        Logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cpp/project1/icons/icons8_logout_rounded_left_30px.png"))); // NOI18N
        Logout.setText("LOGOUT");
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ManageItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Bills, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ManageSuppliers, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
            .addComponent(ManageCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ManageEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(Logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(ManageEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManageSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManageCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManageItems, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bills, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 415, Short.MAX_VALUE)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cpp/project1/icons/icons8_hand_cursor_52px_1.png"))); // NOI18N
        jLabel2.setText("Select an option");

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addGap(521, 521, 521)
                .addComponent(jLabel2)
                .addGap(524, 524, 524))
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addGap(434, 434, 434)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("                ADMIN");
        jLabel1.setOpaque(true);

        AddAdmin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AddAdmin.setForeground(new java.awt.Color(0, 0, 102));
        AddAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cpp/project1/icons/icons8_add_user_group_man_man_52px_1.png"))); // NOI18N
        AddAdmin.setText("Add Admin");
        AddAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddAdmin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                AddAdminMouseMoved(evt);
            }
        });
        AddAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddAdminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(AddAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManageEmployeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageEmployeeMousePressed

    }//GEN-LAST:event_ManageEmployeeMousePressed

    private void ManageEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageEmployeeMouseEntered
        ManageEmployee.setBackground(ClickedColor);
        ManageEmployee.setForeground(DefaultColor);
        ManageEmployee.setIcon(NicME);
    }//GEN-LAST:event_ManageEmployeeMouseEntered

    private void ManageSuppliersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageSuppliersMousePressed
        
    }//GEN-LAST:event_ManageSuppliersMousePressed

    private void ManageItemsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageItemsMousePressed
        
    }//GEN-LAST:event_ManageItemsMousePressed

    private void BillsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BillsMousePressed
        
    }//GEN-LAST:event_BillsMousePressed

    private void ManageEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageEmployeeMouseClicked
        manageEmployees ME=new manageEmployees();
        mainpanel.removeAll();
        mainpanel.add(ME).setVisible(true);
    }//GEN-LAST:event_ManageEmployeeMouseClicked

    private void ManageSuppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageSuppliersMouseClicked
        // TODO add your handling code here:
        manageSuppliers MS=new manageSuppliers();
        mainpanel.removeAll();
        mainpanel.add(MS).setVisible(true);
    }//GEN-LAST:event_ManageSuppliersMouseClicked

    private void ManageItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageItemsMouseClicked
        // TODO add your handling code here:
        manageItems ID=new manageItems();
        mainpanel.removeAll();
        mainpanel.add(ID).setVisible(true);
    }//GEN-LAST:event_ManageItemsMouseClicked

    private void BillsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BillsMouseClicked
        // TODO add your handling code here:
        Bills b=new Bills();
        mainpanel.removeAll();
        mainpanel.add(b).setVisible(true);
    }//GEN-LAST:event_BillsMouseClicked

    private void ManageCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageCategoryMouseClicked
        manageCategory MC=new manageCategory();
        mainpanel.removeAll();
        mainpanel.add(MC).setVisible(true);
    }//GEN-LAST:event_ManageCategoryMouseClicked

    private void ManageCategoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageCategoryMousePressed
        
    }//GEN-LAST:event_ManageCategoryMousePressed

    private void ManageEmployeeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageEmployeeMouseMoved
        
    }//GEN-LAST:event_ManageEmployeeMouseMoved

    private void ManageSuppliersMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageSuppliersMouseMoved
        
    }//GEN-LAST:event_ManageSuppliersMouseMoved

    private void ManageCategoryMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageCategoryMouseMoved
        
    }//GEN-LAST:event_ManageCategoryMouseMoved

    private void ManageItemsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageItemsMouseMoved
        
    }//GEN-LAST:event_ManageItemsMouseMoved

    private void BillsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BillsMouseMoved
        
    }//GEN-LAST:event_BillsMouseMoved

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        int answer=JOptionPane.showConfirmDialog(this,"Are you sure you want to logout?");
        if(answer==0){
            this.dispose();
            Login lgn=new Login();
            lgn.setExtendedState(Login.MAXIMIZED_BOTH);
            lgn.setVisible(true);
        }
    }//GEN-LAST:event_LogoutActionPerformed

    private void ManageEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageEmployeeMouseExited
        ManageEmployee.setBackground(DefaultColor);
        ManageEmployee.setForeground(ClickedColor);
        ManageEmployee.setIcon(icME);
    }//GEN-LAST:event_ManageEmployeeMouseExited

    private void ManageSuppliersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageSuppliersMouseExited
        ManageSuppliers.setBackground(DefaultColor);
        ManageSuppliers.setForeground(ClickedColor);
        ManageSuppliers.setIcon(icMS);
    }//GEN-LAST:event_ManageSuppliersMouseExited

    private void ManageCategoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageCategoryMouseExited
        ManageCategory.setForeground(ClickedColor);
        ManageCategory.setBackground(DefaultColor);
        ManageCategory.setIcon(icMC);
    }//GEN-LAST:event_ManageCategoryMouseExited

    private void ManageItemsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageItemsMouseExited
        ManageItems.setBackground(DefaultColor);
        ManageItems.setForeground(ClickedColor);
        ManageItems.setIcon(icMI);
    }//GEN-LAST:event_ManageItemsMouseExited

    private void BillsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BillsMouseExited
        Bills.setBackground(DefaultColor);
        Bills.setForeground(ClickedColor);
        Bills.setIcon(icB);
    }//GEN-LAST:event_BillsMouseExited

    private void ManageSuppliersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageSuppliersMouseEntered
        ManageSuppliers.setBackground(ClickedColor);
        ManageSuppliers.setForeground(DefaultColor);
        ManageSuppliers.setIcon(NicMS);
    }//GEN-LAST:event_ManageSuppliersMouseEntered

    private void ManageCategoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageCategoryMouseEntered
        ManageCategory.setForeground(DefaultColor);
        ManageCategory.setBackground(ClickedColor);
        ManageCategory.setIcon(NicMC);
    }//GEN-LAST:event_ManageCategoryMouseEntered

    private void ManageItemsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageItemsMouseEntered
        ManageItems.setBackground(ClickedColor);
        ManageItems.setForeground(DefaultColor);
        ManageItems.setIcon(NicMI);
    }//GEN-LAST:event_ManageItemsMouseEntered

    private void BillsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BillsMouseEntered
        Bills.setBackground(ClickedColor);
        Bills.setForeground(DefaultColor);
        Bills.setIcon(NicB);
    }//GEN-LAST:event_BillsMouseEntered

    private void AddAdminMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddAdminMouseMoved

    }//GEN-LAST:event_AddAdminMouseMoved

    private void AddAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddAdminMouseClicked
        Admin_Signup asp=new Admin_Signup();
        asp.setExtendedState(Admin_Signup.MAXIMIZED_BOTH);
        asp.setVisible(true);
        asp.LoginPage.setVisible(false);
        asp.Back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddAdminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                admin admin = new admin();
                admin.setExtendedState(admin.MAXIMIZED_BOTH);
                admin.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddAdmin;
    private javax.swing.JLabel Bills;
    private javax.swing.JButton Logout;
    private javax.swing.JLabel ManageCategory;
    private javax.swing.JLabel ManageEmployee;
    private javax.swing.JLabel ManageItems;
    private javax.swing.JLabel ManageSuppliers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainpanel;
    // End of variables declaration//GEN-END:variables
}

