  /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cpp.project1;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Priyansh
 */
public class manageCategory extends javax.swing.JInternalFrame {

    /**
     * Creates new form manageCategory
     */
    Connection Con= null;
    Statement St= null;
    ResultSet Rs=null;
    public void SelectCategory()
    {
        try{
            Con=DriverManager.getConnection("jdbc:derby://localhost:1527/grocerystoredb","User1","1234");
            St=Con.createStatement();
            Rs=St.executeQuery("Select * from User1.MANAGECATEGORYTB");
            CatTable.setModel(DbUtils.resultSetToTableModel(Rs));
            theader();
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    public manageCategory() {
        initComponents();
        SelectCategory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        CatSearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        CatTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        CatDelete = new javax.swing.JButton();
        CatDes = new javax.swing.JTextField();
        CatAdd = new javax.swing.JButton();
        CatClear = new javax.swing.JButton();
        CatName = new javax.swing.JTextField();
        CatId = new javax.swing.JTextField();
        CatUpdate = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1491, 1000));

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(1187, 717));

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));

        jLabel5.setBackground(new java.awt.Color(0, 0, 102));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cpp/project1/icons/icons8_list_52px.png"))); // NOI18N
        jLabel5.setText("MANAGE CATEGORY");
        jLabel5.setOpaque(true);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        CatSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CatSearch.setForeground(new java.awt.Color(153, 153, 153));
        CatSearch.setText("  Search Item");
        CatSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 102)));
        CatSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CatSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CatSearchFocusLost(evt);
            }
        });
        CatSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatSearchActionPerformed(evt);
            }
        });
        CatSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CatSearchKeyReleased(evt);
            }
        });

        CatTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CategoryId", "CategoryName", "CategoryDescription"
            }
        ));
        CatTable.setRowHeight(35);
        CatTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CatTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(CatTable);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CatSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(CatSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        CatDelete.setBackground(new java.awt.Color(0, 0, 102));
        CatDelete.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CatDelete.setForeground(new java.awt.Color(255, 255, 255));
        CatDelete.setText("DELETE");
        CatDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatDeleteActionPerformed(evt);
            }
        });

        CatDes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CatDes.setForeground(new java.awt.Color(153, 153, 153));
        CatDes.setText("  Enter Category Description");
        CatDes.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 102)));
        CatDes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CatDesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CatDesFocusLost(evt);
            }
        });
        CatDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatDesActionPerformed(evt);
            }
        });

        CatAdd.setBackground(new java.awt.Color(0, 0, 102));
        CatAdd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CatAdd.setForeground(new java.awt.Color(255, 255, 255));
        CatAdd.setText("ADD");
        CatAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatAddActionPerformed(evt);
            }
        });

        CatClear.setBackground(new java.awt.Color(0, 0, 102));
        CatClear.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CatClear.setForeground(new java.awt.Color(255, 255, 255));
        CatClear.setText("CLEAR");
        CatClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatClearActionPerformed(evt);
            }
        });

        CatName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CatName.setForeground(new java.awt.Color(153, 153, 153));
        CatName.setText("  Enter Category Name");
        CatName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 102)));
        CatName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CatNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CatNameFocusLost(evt);
            }
        });
        CatName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatNameActionPerformed(evt);
            }
        });

        CatId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CatId.setForeground(new java.awt.Color(153, 153, 153));
        CatId.setText("  Enter Category Id");
        CatId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 102)));
        CatId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CatIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CatIdFocusLost(evt);
            }
        });
        CatId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatIdActionPerformed(evt);
            }
        });

        CatUpdate.setBackground(new java.awt.Color(0, 0, 102));
        CatUpdate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CatUpdate.setForeground(new java.awt.Color(255, 255, 255));
        CatUpdate.setText("UPDATE");
        CatUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CatDes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CatName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                        .addComponent(CatId, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CatAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CatDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CatClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CatUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(CatId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CatName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CatDes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CatAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CatUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CatDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CatClear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 1475, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void theader()
         {
             JTableHeader thead =CatTable.getTableHeader();
             thead.setForeground(new Color(0,0,102));
             thead.setFont(new Font("Tahoma",Font.BOLD,14));
         }
    private void CatIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CatIdFocusGained
        if(CatId.getText().equals("  Enter Category Id"))
        {
            CatId.setText("");
            CatId.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_CatIdFocusGained

    private void CatIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CatIdFocusLost
        if(CatId.getText().equals(""))
        {
            CatId.setText("  Enter Category Id");
            CatId.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_CatIdFocusLost

    private void CatIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatIdActionPerformed

    private void CatNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CatNameFocusGained
        if(CatName.getText().equals("  Enter Category Name"))
        {
            CatName.setText("");
            CatName.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_CatNameFocusGained

    private void CatNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CatNameFocusLost
        if(CatName.getText().equals(""))
        {
            CatName.setText("  Enter Category Name");
            CatName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_CatNameFocusLost

    private void CatDesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CatDesFocusGained
        if(CatDes.getText().equals("  Enter Category Description"))
        {
            CatDes.setText("");
            CatDes.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_CatDesFocusGained

    private void CatDesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CatDesFocusLost
        if(CatDes.getText().equals(""))
        {
            CatDes.setText("  Enter Category Description");
            CatDes.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_CatDesFocusLost

    private void CatDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatDesActionPerformed

    private void CatAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatAddActionPerformed
        if(CatId.getText().isEmpty()||CatName.getText().isEmpty()||CatDes.getText().isEmpty()||"  Enter Category Id".equals(CatId.getText())||"  Enter Category Name".equals(CatName.getText())||"  Enter Category Description".equals(CatDes.getText()))
        {
            JOptionPane.showMessageDialog(this, "Missing Information");
        }
        else{
            try {
                Con = DriverManager.getConnection("jdbc:derby://localhost:1527/grocerystoredb","User1","1234");
                PreparedStatement add = Con.prepareStatement("insert into MANAGECATEGORYTB values (?,?,?)");
                add.setString(1,CatId.getText());// TODO add your handling code here:
                add.setString(2,CatName.getText());
                add.setString(3,CatDes.getText());
                int row;
                row = add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Category Added Successfully");
                Con.close();
                SelectCategory();
            }
            catch (Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_CatAddActionPerformed

    private void CatUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatUpdateActionPerformed
        if(CatId.getText().isEmpty()||CatName.getText().isEmpty()||CatDes.getText().isEmpty()||"  Enter Category Id".equals(CatId.getText())||"  Enter Category Name".equals(CatName.getText())||"  Enter Category Description".equals(CatDes.getText()))
        {
            JOptionPane.showMessageDialog(this, "Missing Information");
        }
        else{
            try {
                Con = DriverManager.getConnection("jdbc:derby://localhost:1527/grocerystoredb","User1","1234");
                String Query = "Update User1.MANAGECATEGORYTB set CATEGORY_NAME='"+CatName.getText()+"'"+",CATEGORY_DESCRIPTION='"+CatDes.getText()+"'"+"where CATEGORY_ID='"+CatId.getText()+"'";
                Statement Add=Con.createStatement();
                Add.executeUpdate(Query);
                SelectCategory();
                JOptionPane.showMessageDialog(this, "Category Updated");
            }
            catch (Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_CatUpdateActionPerformed

    private void CatDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatDeleteActionPerformed
        if(CatId.getText().isEmpty()||"  Enter Category Id".equals(CatId.getText()))
        {
            JOptionPane.showMessageDialog(this, "Enter the Category Id to Delete the Category");
        }
        else{
            try{
                Con = DriverManager.getConnection("jdbc:derby://localhost:1527/grocerystoredb","User1","1234");
                String CID=CatId.getText();
                String Query="Delete from User1.MANAGECATEGORYTB where CATEGORY_ID='"+CID+"'";
                Statement Add=Con.createStatement();
                Add.executeUpdate(Query);
                SelectCategory();
                JOptionPane.showMessageDialog(this, "Category Deleted Successfully");
            }catch(Exception e)
            {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_CatDeleteActionPerformed

    private void CatClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatClearActionPerformed
        CatId.setText("  Enter Category Id");
        CatId.setForeground(new Color(153,153,153));
        CatName.setText("  Enter Category Name");
        CatName.setForeground(new Color(153,153,153));
        CatDes.setText("  Enter Category Description");
        CatDes.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_CatClearActionPerformed

    private void CatSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CatSearchFocusGained
        if(CatSearch.getText().equals("  Search Item"))
        {
            CatSearch.setText("");
            CatSearch.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_CatSearchFocusGained

    private void CatSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CatSearchFocusLost
        if(CatSearch.getText().equals(""))
        {
            CatSearch.setText("  Search Item");
            CatSearch.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_CatSearchFocusLost

    private void CatSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatSearchActionPerformed

    private void CatSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CatSearchKeyReleased
        DefaultTableModel Model=(DefaultTableModel) CatTable.getModel();
        String search = CatSearch.getText();
        TableRowSorter<DefaultTableModel> tr= new TableRowSorter <DefaultTableModel>(Model);
        CatTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_CatSearchKeyReleased

    private void CatTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CatTableMouseClicked
        DefaultTableModel Model=(DefaultTableModel) CatTable.getModel();
        int Myindex = CatTable.getSelectedRow();
        CatId.setText(Model.getValueAt(Myindex,0).toString());
        CatId.setForeground(new Color(0,0,0));
        CatName.setText(Model.getValueAt(Myindex,1).toString());
        CatName.setForeground(new Color(0,0,0));
        CatDes.setText(Model.getValueAt(Myindex,2).toString());
        CatDes.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_CatTableMouseClicked

    private void CatNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CatAdd;
    private javax.swing.JButton CatClear;
    private javax.swing.JButton CatDelete;
    private javax.swing.JTextField CatDes;
    private javax.swing.JTextField CatId;
    private javax.swing.JTextField CatName;
    private javax.swing.JTextField CatSearch;
    private javax.swing.JTable CatTable;
    private javax.swing.JButton CatUpdate;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
